#!/bin/bash

java -Droutes='[{"vhost": "test1.localdomain","backend":"http://localhost:5001"},{"vhost": "test2.localdomain","backend":"http://localhost:5002"}]' -jar basic-http-proxy.jar -Xms512m -Xmx820m -server -XX:PermSize=128m -XX:MaxPermSize=128m -XX:MaxGCPauseMillis=100 -XX:+UseConcMarkSweepGC -XX:ParallelCMSThreads=2 -XX:+CMSClassUnloadingEnabled -XX:+UseCMSCompactAtFullCollection -XX:CMSInitiatingOccupancyFraction=80
