#!/bin/bash

java -jar basic-http-proxy.jar -Xms512m -Xmx820m -server -XX:PermSize=128m -XX:MaxPermSize=128m -XX:MaxGCPauseMillis=100 -XX:+UseConcMarkSweepGC -XX:ParallelCMSThreads=2 -XX:+CMSClassUnloadingEnabled -XX:+UseCMSCompactAtFullCollection -XX:CMSInitiatingOccupancyFraction=80